---
- name: Restart and Verify Nginx Service
  hosts: webservers
  become: yes  # Use privilege escalation (sudo) to manage the service
  tasks:
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: restarted  # Restart the Nginx service

    - name: Verify Nginx is running
      shell: systemctl status nginx | grep 'active (running)'
      register: nginx_status  # Register the result of the command
      changed_when: false  # Do not consider this task as "changed" in playbook reporting
      failed_when: nginx_status.rc != 0  # Fail the task if Nginx is not running

    - name: Print Nginx status
      debug:
        msg: "Nginx service is running."  # Print a success message
      when: nginx_status.rc == 0  # Only print the message if the status check was successful
